# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/mainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setMinimumSize(QtCore.QSize(400, 720))
        self.dropShadowFrame.setStyleSheet("#dropShadowFrame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0.975369, y2:0.0340909, stop:0 rgba(9, 0, 113, 255), stop:0.852217 rgba(89, 0, 108, 255));\n"
"}\n"
"\n"
"")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dropShadowFrame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.dropShadowFrame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_3.setStyleSheet("border: 0;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Abnes")
        font.setPointSize(44)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white; \n"
"font: \"Abnes\";\n"
"dropShadowFrame")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Megrim")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;n")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Earth Orbiter")
        font.setPointSize(18)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("border:0;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 233))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 180))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        self.pushButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"border-radius: 90px;\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0.975369, y2:0.0340909, stop:0 rgba(3, 4, 64, 255), stop:0.852217 rgba(49, 3, 61, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0.975369, y2:0.0340909, stop:0 rgba(2, 4, 48, 255), stop:0.852217 rgba(40, 3, 50, 255))\n"
"\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/assets/white-mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(140, 140))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Earth Orbiter")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;\n"
"font: 20pt \"Earth Orbiter\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Earth Orbiter")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 230))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: 20pt \"Geneva\";")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(340, 50))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.NewClientStateSelection = QtWidgets.QComboBox(self.frame_10)
        self.NewClientStateSelection.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewClientStateSelection.sizePolicy().hasHeightForWidth())
        self.NewClientStateSelection.setSizePolicy(sizePolicy)
        self.NewClientStateSelection.setMinimumSize(QtCore.QSize(0, 40))
        self.NewClientStateSelection.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.NewClientStateSelection.setFont(font)
        self.NewClientStateSelection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NewClientStateSelection.setStyleSheet("QComboBox{\n"
"  border: 2px solid rgb(0, 0, 96);\n"
"  border-radius: 20px;\n"
"  color: #FFF; \n"
"  padding-left: 20px;\n"
"  padding-right: 0px;\n"
"  background-color:rgb(0, 0, 96);\n"
"}\n"
"QComboBox::drop-down{\n"
"  background-color: transparent;\n"
"  width: 40px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"color: white;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid white;\n"
"  border-radius: 5px;\n"
"  selection-background-color: rgb(0, 0, 96);\n"
"  font: 15pt \"Geneva\";\n"
"  color: rgb(0, 0, 96);\n"
"  selection-color: white;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"  min-height: 50px;\n"
"  border: 5px solid white;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    background-color: rgb(108, 135, 158);\n"
"    border: 2px solid rgb(108, 135, 158);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(0,0,96);\n"
"    padding-right: 15px;\n"
"    font: 15pt \"Geneva\";\n"
"    color:white;\n"
"}\n"
"")
        self.NewClientStateSelection.setEditable(True)
        self.NewClientStateSelection.setObjectName("NewClientStateSelection")
        self.horizontalLayout_4.addWidget(self.NewClientStateSelection)
        self.verticalLayout_8.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 145))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.frame_12)
        self.radioButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton.setStyleSheet("color: white")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_12)
        self.radioButton_2.setMaximumSize(QtCore.QSize(90, 35))
        self.radioButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout_9.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 59))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(63, 16777215))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.NewClientName = QtWidgets.QLineEdit(self.frame_13)
        self.NewClientName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewClientName.sizePolicy().hasHeightForWidth())
        self.NewClientName.setSizePolicy(sizePolicy)
        self.NewClientName.setMinimumSize(QtCore.QSize(0, 40))
        self.NewClientName.setMaximumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(11)
        self.NewClientName.setFont(font)
        self.NewClientName.setStyleSheet("QLineEdit {\n"
"border: 2px solid rgb(0, 0, 96);\n"
"border-radius: 20px;\n"
"color: #FFF; \n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color:rgb(0, 0, 96);\n"
"} \n"
"\n"
"QLineEdit:enabled {\n"
"border: 2px solid rgb(0, 0, 96);\n"
"border-radius: 20px;\n"
"color: #FFF; \n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color:rgb(0, 0, 96);\n"
"} \n"
"\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgb(108, 135, 158);\n"
"    border: 2px solid rgb(108, 135, 158);\n"
"}\n"
"\n"
"QLineEdit:hover { \n"
"border: 2px solid rgb(15, 102, 255); \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
" border: 2px solid rgb(85, 170, 255);\n"
" background-color: rgb(0, 0, 96);\n"
"}")
        self.NewClientName.setObjectName("NewClientName")
        self.horizontalLayout_5.addWidget(self.NewClientName)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 23pt \"Futura Bk BT\";\n"
"color: rgb(34, 255, 61)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.dropShadowFrame)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border:0;\n"
"color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(23)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Earth Orbiter")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FRIDAY"))
        self.label_2.setText(_translate("MainWindow", "A HACKABLE IOT ASSISTANT"))
        self.label_6.setText(_translate("MainWindow", "LISTENING..."))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Geneva\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">START SPEAKING SOMETHING</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "GPIO:"))
        self.NewClientStateSelection.setItemText(0, _translate("MainWindow", "CHANNEL 2"))
        self.NewClientStateSelection.setItemText(1, _translate("MainWindow", "CHANNEL 3"))
        self.NewClientStateSelection.setItemText(2, _translate("MainWindow", "CHANNEL 4"))
        self.NewClientStateSelection.setItemText(3, _translate("MainWindow", "CHANNEL 5"))
        self.NewClientStateSelection.setItemText(4, _translate("MainWindow", "CHANNEL 6"))
        self.NewClientStateSelection.setItemText(5, _translate("MainWindow", "CHANNEL 7"))
        self.NewClientStateSelection.setItemText(6, _translate("MainWindow", "CHANNEL 8"))
        self.NewClientStateSelection.setItemText(7, _translate("MainWindow", "CHANNEL 9"))
        self.NewClientStateSelection.setItemText(8, _translate("MainWindow", "CHANNEL 10"))
        self.NewClientStateSelection.setItemText(9, _translate("MainWindow", "CHANNEL 11"))
        self.NewClientStateSelection.setItemText(10, _translate("MainWindow", "CHANNEL 12"))
        self.NewClientStateSelection.setItemText(11, _translate("MainWindow", "CHANNEL 13"))
        self.NewClientStateSelection.setItemText(12, _translate("MainWindow", "CHANNEL 16"))
        self.NewClientStateSelection.setItemText(13, _translate("MainWindow", "CHANNEL 17"))
        self.NewClientStateSelection.setItemText(14, _translate("MainWindow", "CHANNEL 18"))
        self.NewClientStateSelection.setItemText(15, _translate("MainWindow", "CHANNEL 19"))
        self.NewClientStateSelection.setItemText(16, _translate("MainWindow", "CHANNEL 20"))
        self.NewClientStateSelection.setItemText(17, _translate("MainWindow", "CHANNEL 21"))
        self.NewClientStateSelection.setItemText(18, _translate("MainWindow", "CHANNEL 22"))
        self.NewClientStateSelection.setItemText(19, _translate("MainWindow", "CHANNEL 23"))
        self.NewClientStateSelection.setItemText(20, _translate("MainWindow", "CHANNEL 24"))
        self.NewClientStateSelection.setItemText(21, _translate("MainWindow", "CHANNEL 25"))
        self.NewClientStateSelection.setItemText(22, _translate("MainWindow", "CHANNEL 26"))
        self.NewClientStateSelection.setItemText(23, _translate("MainWindow", "CHANNEL 27"))
        self.radioButton.setText(_translate("MainWindow", "DIGITAL"))
        self.radioButton_2.setText(_translate("MainWindow", "ANALOG"))
        self.label_9.setText(_translate("MainWindow", "VALUE:"))
        self.label_5.setText(_translate("MainWindow", "CONNECTED"))
        self.label_4.setText(_translate("MainWindow", "  ©"))
        self.label_3.setText(_translate("MainWindow", " Ansh Patel · All Rights Reserved"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
